version: '3.8'
services: 
  app: 
    container_name : hisaabkitaab-server
    build: .
    ports: 
      - "5000:5000"
    env_file:
      - .env
    restart: 
      always
    volumes: 
      - ./logs:/app/logs
    networks:
      - hisaabkitaabnet
    depends_on:
      - ai-service

  ai-service:
    image: chandannn/hisaabkitaab-ai-service:latest
    container_name: ai-service
    env_file:
      - /srv/hisaabkitaab-ai-service/.env
    volumes:
      - /srv/hisaabkitaab-ai-service/vector_store:/app/vector_store/storage
    restart: unless-stopped
    networks:
      - hisaabkitaabnet
  